### ISSUE TITLE
Plugins not installing

### ISSUE THREAD

**Issue by tyler-barnes** [xfiveco/generator-chisel#201]
When I run the generator it doesn't install timber. I've also set Select optional plugins to: Advanced Custom Fields Pro, Gravity Forms, WP Sync DB, WP Sync DB Media File Addon. None of these install either.

At the end of the generator I got this error 
`/usr/local/lib/node_modules/generator-chisel/helpers/index.js:19
        throw err;
        ^
Error when checking database,,sh: mysqlcheck: command not found`

Is there something I can do to fix this?

**Comment by jakub300** [comment]
Hey,
You need to have `mysql` and `mysqlcheck` binaries in your `$PATH`. Chisel is using WP-CLI for most WP-related operations. Unfortunately WP-CLI is using `mysql` and `mysqlcheck` binaries, not mysql(i) php extension for database operations.

**Comment by luboskmetko** [comment]
I've updated README with the info about `mysql` and `mysqlcheck` binaries.

@tyler-barnes please let us know if it helped and if we can close this issue.

**Comment by tyler-barnes** [comment]
@luboskmetko Thanks for the info. That doesn't seem to fix the issue though.

Here's everything printed to the terminal during the scaffolding
`Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo chisel


 *********************************************

  Welcome to Chisel

  https://github.com/xfiveco/generator-chisel

 *********************************************

? Please enter the project name: Chisel
? Please enter author name: Tyler
? Please select project type: WordPress with Front-end
? Select additional front-end features: jQuery, ES2015 with Babel

WORDPRESS SETUP

? Enter title for the new site: Chisel
? Enter URL: http://chisel.dev/
? Enter admin user: admin
? Enter admin password: *****
? Enter admin email: tyler@bare.ca
? Where do you want to place the 'src' folder: Project root folder
? Enter the database host: 127.0.0.1
? Enter the database name: chisel
? Enter the database user: root
? Enter the database password: ****
? Select optional plugins Advanced Custom Fields Pro, Gravity Forms, WP Sync DB,
 WP Sync DB Media File Addon

INSTALLATION



I'm all done. Running yarn install for you to install the required dependencies. If this fails, try running the command yourself.


   create package.json
   create .editorconfig
   create .eslintrc.yml
   create .gitattributes
   create .htmlhintrc
   create .stylelintrc.yml
   create .gitignore
   create src/assets/fonts/.keep
   create src/assets/images/.keep
   create README.md
   create src/styles/components/_btn.scss
   create src/styles/components/_footer.scss
   create src/styles/components/_header.scss
   create src/styles/components/_style-guide.scss
   create src/styles/elements/_blockquote.scss
   create src/styles/elements/_headings.scss
   create src/styles/elements/_hr.scss
   create src/styles/elements/_html.scss
   create src/styles/elements/_images.scss
   create src/styles/elements/_links.scss
   create src/styles/elements/_lists.scss
   create src/styles/elements/_tables.scss
   create src/styles/generic/_box-sizing.scss
   create src/styles/generic/_normalize.scss
   create src/styles/generic/_reset.scss
   create src/styles/generic/_shared.scss
   create src/styles/main.scss
   create src/styles/objects/_layout.scss
   create src/styles/objects/_list-bare.scss
   create src/styles/objects/_list-inline.scss
   create src/styles/objects/_media.scss
   create src/styles/objects/_table.scss
   create src/styles/objects/_wrapper.scss
   create src/styles/settings/_global.scss
   create src/styles/tools/_breakpoints.scss
   create src/styles/tools/_clearfix.scss
   create src/styles/tools/_hidden.scss
   create src/styles/utilities/_align.scss
   create src/styles/utilities/_clearfix.scss
   create src/styles/utilities/_color.scss
   create src/styles/utilities/_hide.scss
   create src/styles/utilities/_spacing.scss
   create src/scripts/app.js
   create src/scripts/greeting.js
   create gulpfile.js
   create gulp/helpers.js
   create gulp/prepareConfig.js
   create gulp/tasks/assets.js
   create gulp/tasks/build.js
   create gulp/tasks/lint.js
   create gulp/tasks/scripts.js
   create gulp/tasks/serve.js
   create gulp/tasks/styles.js
   create gulp/tasks/templates.js
   create gulp/templatesFunctions.js
   create dev-vhost.conf
Downloading WordPress 4.8 (en_US)...
md5 hash verified: b91248a7220a7fb1ca293c3a0ec8db6c
Success: WordPress downloaded.
   create wp/wp-content/themes/chisel/404.php
   create wp/wp-content/themes/chisel/archive.php
   create wp/wp-content/themes/chisel/author.php
   create wp/wp-content/themes/chisel/features/ChiselPost.php
   create wp/wp-content/themes/chisel/footer.php
   create wp/wp-content/themes/chisel/functions.php
   create wp/wp-content/themes/chisel/header.php
   create wp/wp-content/themes/chisel/index.php
   create wp/wp-content/themes/chisel/page.php
   create wp/wp-content/themes/chisel/README.md
   create wp/wp-content/themes/chisel/search.php
   create wp/wp-content/themes/chisel/single.php
   create wp/wp-content/themes/chisel/style.css
   create wp/wp-content/themes/chisel/templates/404.twig
   create wp/wp-content/themes/chisel/templates/author.twig
   create wp/wp-content/themes/chisel/templates/components/comment.twig
   create wp/wp-content/themes/chisel/templates/components/main-nav.twig
   create wp/wp-content/themes/chisel/templates/components/tease-post.twig
   create wp/wp-content/themes/chisel/templates/components/tease.twig
   create wp/wp-content/themes/chisel/templates/index.twig
   create wp/wp-content/themes/chisel/templates/page-plugin.twig
   create wp/wp-content/themes/chisel/templates/page.twig
   create wp/wp-content/themes/chisel/templates/single.twig
   create wp/wp-content/themes/chisel/screenshot.png
   create wp/wp-content/themes/chisel/templates/components/btn.twig
   create wp/wp-content/themes/chisel/templates/components/footer.twig
   create wp/wp-content/themes/chisel/templates/components/header.twig
   create wp/wp-content/themes/chisel/templates/elements/blockquote.twig
   create wp/wp-content/themes/chisel/templates/elements/headings.twig
   create wp/wp-content/themes/chisel/templates/elements/hr.twig
   create wp/wp-content/themes/chisel/templates/elements/images.twig
   create wp/wp-content/themes/chisel/templates/elements/links.twig
   create wp/wp-content/themes/chisel/templates/elements/lists.twig
   create wp/wp-content/themes/chisel/templates/elements/tables.twig
   create wp/wp-content/themes/chisel/templates/layouts/base.twig
   create wp/wp-content/themes/chisel/templates/layouts/page.twig
   create wp/wp-content/themes/chisel/templates/objects/layout.twig
   create wp/wp-content/themes/chisel/templates/objects/list-bare.twig
   create wp/wp-content/themes/chisel/templates/objects/list-inline.twig
   create wp/wp-content/themes/chisel/templates/objects/media.twig
   create wp/wp-content/themes/chisel/templates/objects/table.twig
   create wp/wp-content/themes/chisel/templates/utilities/align.twig
   create wp/wp-content/themes/chisel/templates/page-style-guide.twig
   create wp/wp-content/themes/chisel/.gitignore
   create src/styles/components/_comment-form.scss
   create src/styles/components/_comment.scss
   create src/styles/components/_main-nav.scss
   create src/styles/components/_post.scss
Local config generated
yarn install v0.24.6
info No lockfile found.
warning chisel@0.0.1: No license field
[1/4] 🔍  Resolving packages...
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp-htmlhint > htmlhint > jshint > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp-htmlhint > htmlhint > jshint > cli > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning browser-sync > localtunnel > request > node-uuid@1.4.8: Use uuid module instead
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[2/4] 🚚  Fetching packages...
██████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 247/91███████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 250/91█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 71████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░ ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 149.64s.

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 


/usr/local/lib/node_modules/generator-chisel/helpers/index.js:19
        throw err;
        ^
Error when checking database,,sh: mysqlcheck: command not found
`

**Comment by luboskmetko** [comment]
@tyler-barnes thanks for the additional info. Can you please check yet if you can run the `mysqlcheck` from the command line:

```
mysqlcheck -V
```

Also can you update to the latest version of Chisel which is 0.6.4?

```
npm i -g generator-chisel
```

You can find out which version you currently have with: 

```
npm list -g --depth=0 generator-chisel
```

(According the scaffolding options it seems you have some older version.)

Let's see if any of these helps before we investigate further. 

Thanks

**Comment by luboskmetko** [comment]
Closing this one as we haven't got additional info.

**Comment by duezerouno** [comment]
Hello guys, I included `mysql` and `mysqlcheck` into my `$PATH` but I think I didn't quite get it as `mysqlcheck -V` returns `not found`. Any idea?

echo $PATH output

`/Library/Frameworks/Python.framework/Versions/3.6/bin:/Applications/MAMP/Library/bin/mysqlcheck:/Applications/MAMP/Library/bin/mysql:/Users/andrea/.yarn/bin:/Users/andrea/.rvm/gems/ruby-2.4.0/bin:/Users/andrea/.rvm/gems/ruby-2.4.0@global/bin:/Users/andrea/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/andrea/.rvm/bin`

**Comment by jakub300** [comment]
Hey Andrea @duezerouno,

`$PATH` should contain list of directories in which system will look for programs, not full paths to executables. In your case you should add `/Applications/MAMP/Library/bin`, not `/Applications/MAMP/Library/bin/mysqlcheck` and `/Applications/MAMP/Library/bin/mysql`.
